use_frameworks!

platform :ios, '12.0'

target 'ZKAppDelegateSOA_Example' do
  pod 'ZKAppDelegateSOA', :path => '../'
  
#  target 'ZKAppDelegateSOA_Tests' do
#    inherit! :search_paths
#    
#    pod 'FBSnapshotTestCase'
#  end
end
